// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM0MbpmhkBhRK5XCcuTpigjy7pluTZPcQ',
    appId: '1:269433776834:web:1b9508fdefa4a6465f695b',
    messagingSenderId: '269433776834',
    projectId: 'trade-hub-app',
    authDomain: 'trade-hub-app.firebaseapp.com',
    storageBucket: 'trade-hub-app.firebasestorage.app',
    measurementId: 'G-7ZQQ3CTQMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIFyf1dto3xgbEOE6OW7WMxuNlo5BTVOQ',
    appId: '1:269433776834:android:1be7c6e7e95e6bd65f695b',
    messagingSenderId: '269433776834',
    projectId: 'trade-hub-app',
    storageBucket: 'trade-hub-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdFmNVBaN6vOH8VHHDpGu7MkAIQ-HQlnM',
    appId: '1:269433776834:ios:77a5db0cf84bf1f75f695b',
    messagingSenderId: '269433776834',
    projectId: 'trade-hub-app',
    storageBucket: 'trade-hub-app.firebasestorage.app',
    androidClientId: '269433776834-f20jr2afilu7gb33q9vl1v8uggp2lh09.apps.googleusercontent.com',
    iosClientId: '269433776834-upqfoco3rmkjp119rlvskqkj5r43qjiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradeHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdFmNVBaN6vOH8VHHDpGu7MkAIQ-HQlnM',
    appId: '1:269433776834:ios:77a5db0cf84bf1f75f695b',
    messagingSenderId: '269433776834',
    projectId: 'trade-hub-app',
    storageBucket: 'trade-hub-app.firebasestorage.app',
    androidClientId: '269433776834-f20jr2afilu7gb33q9vl1v8uggp2lh09.apps.googleusercontent.com',
    iosClientId: '269433776834-upqfoco3rmkjp119rlvskqkj5r43qjiv.apps.googleusercontent.com',
    iosBundleId: 'com.example.tradeHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM0MbpmhkBhRK5XCcuTpigjy7pluTZPcQ',
    appId: '1:269433776834:web:fbb6c3b3be7e797e5f695b',
    messagingSenderId: '269433776834',
    projectId: 'trade-hub-app',
    authDomain: 'trade-hub-app.firebaseapp.com',
    storageBucket: 'trade-hub-app.firebasestorage.app',
    measurementId: 'G-V6KD96J68X',
  );
}
